---
- hosts: all
  collections: 
    - community.general
  gather_facts: yes
  become: true
  tasks:
  - name: Registar las maquinas al pool XXXXX SKU
    redhat_subscription:
      state: present
      username: "{{ rhuser }}"
      password: "{{ passwd }}"
      auto_attach: true
      force_register: true


  - name: Instalar paquete de Red Hat Insights
    yum:
      name: insights-client
      state: latest

  - name: Registrar maquina en insights
    shell: insights-client --register
    register: salida

  - name: Mensaje de salida registro
    debug:
      var: salida
